events {}

http {
    upstream backend_servers {
        server app1:8000;
        server app2:8001;
        server app3:8002;
        server app4:8003;
        server app5:8004;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}